### PR TITLE
Mysql code rewrite

### PR DESCRIPTION
**Pull request by karate**
I rewrote the `dbSearcher::dbs_search()` method.
Please review and let me know if you need any changes.

This needs https://github.com/PatricNox/DatabaseSearcher/pull/14 to be merged

### CODE REVIEW

**Comment by PatricNox** [comment]
Hello!

Thank you for this, neat!

However this isn't bulletproof. 
While quering, I get

`SELECT * FROM cache WHERE data LIKE "%kodamera%" ;`

Should not be a LIKE expression here, if we are to rework the current process.

Also, when quering with strict mode, you end up with results such as this:

`block | 785 | SELECT * FROM block WHERE ;`

**Comment by PatricNox** [comment]
Actually, my bad, i didn't check out to this PR branch when using your remote.

It works flawlessly! Though still would want the expression change upon strict mode.

Thanks alot! <3

**Comment by PatricNox** [comment]
Fixes https://github.com/PatricNox/DatabaseSearcher/issues/16 https://github.com/PatricNox/DatabaseSearcher/issues/15

**Comment by karate** [comment]
I'm a little confused.
You want the expression shown in the table to be `=` instead of `LIKE`, when the strict-mode is not enabled?

**Comment by karate** [comment]
Just a friendly comment for a better git history:

There was no need to close https://github.com/PatricNox/DatabaseSearcher/pull/14. It included commits about "Strict mode improvements" which are unrelated to `dbSearcher::dbs_search()` rewrite, and would provide a better git history. The commits from https://github.com/PatricNox/DatabaseSearcher/pull/14 visible here (just because I created this branch from `strict-mode-improvements`) would be ignored during merge. :wink:

**Comment by PatricNox** [comment]
You want the expression shown in the table to be = instead of LIKE, when the strict-mode **is** enabled. :) 

Thanks for all the help!

**Comment by karate** [comment]
>  when the strict-mode **is** enabled. 

Yes. That's what I meant :P
Do you want to apply the same change in the actual query run (https://github.com/PatricNox/DatabaseSearcher/pull/17/commits/dfce730cde585bd221739cab723e02e216c3577c#diff-fa362893ac9b022c2cff82aa7564e45dR78)?

**Comment by karate** [comment]
Putting quotes in the search keyword like you suggested, returns the following warning: `Truncated incorrect DOUBLE value: 'search_keyword'`, when you have a non-string column in the `WHERE` clause, and the search_keyword is not a number. 

This returns some false positive results.

Maybe we should check the column type, and only add a `WHERE` clause when it makes sense.

**Comment by PatricNox** [comment]
hmm yeah, that's a good idea

**Comment by karate** [comment]
I'm not sure about the best way to do this.
We have the column type from `"SHOW COLUMNS FROM $table"` but MySQL has many types for numbers and strings (`TINYINT`, `SMALLINT`, `INT`, `DECIMAL`, `BIT`, `CHAR`, `VARCHAR`, `TEXT` etc). Any ideas?

**Comment by karate** [comment]
@PatricNox I can confirm that if we use the `=` operator (like the original code) instead of `LIKE` (as in the current PR), we get the bug above (false positive results and broken expressions in strict mode).

The `=` operator may be a little faster sometimes, but compared to manually checking all column types, I think it's a better choice.

I also checked `phpmyadmin`'s search functionality, and it uses the `LIKE` operator, even when searching for the exact string.

**Comment by PatricNox** [comment]
Let's keep it as LIKE then. :)

**Pull request merged**
